name: 'Install phylum latest'
description: 'Install the latest version of the phylum command-line tool'
inputs:
  phylum_username:
    description: "Phylum username"
    required: true
  phylum_password:
    description: "Phylum password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download latest phylum release
      shell: bash
      run: curl --silent "https://api.github.com/repos/phylum-dev/cli/releases/latest" | jq -r '.assets[] | select(.name | contains("phylum-cli-release.zip")) | .browser_download_url' | xargs curl -sLo ~/phylum-cli-release.zip

    - name: Run install script
      shell: bash
      run: |
        unzip ~/phylum-cli-release.zip -d ~
        export PATH="$HOME/phylum-cli-release:$PATH"
        pushd "$HOME/phylum-cli-release" || exit 1
          bash install.sh
        popd
        echo "[*] installed phylum"

    - name: Setup credentials
      shell: bash
      run: |
        sed -i "s/user:.*/user: ${{ inputs.phylum_username }}/" ~/.phylum/settings.yaml
        sed -i "s/pass:.*/pass: ${{ inputs.phylum_password }}/" ~/.phylum/settings.yaml
        echo "[*] Configured phylum with credentials"

    - name: Test phylum
      shell: bash
      run: |
        export PATH="$HOME/.phylum:$PATH"
        pushd $GITHUB_WORKSPACE || exit 1
          phylum --help
        popd

